Feat/rename table
manticoresoftware/manticoresearch-buddy pull request #260
Opened 2024-04-25 12:44 UTC by djklim87

2024-04-26 11:01 UTC, donhardman requested changes
We should move this plugin into the `buddy-plugin-modify-table`, because that plugin is designed to handle table modifications (including alters).

2024-05-09 10:48 UTC, djklim87 commented on src/Plugin/RenameTable/Payload.php
> +		$payload = Payload::$sqlQueryParser::parse($request->payload);
done

2024-05-09 10:49 UTC, djklim87 commented
> We should move this plugin into the `buddy-plugin-modify-table`, because that plugin is designed to handle table modifications (including alters).

As discussed at last dev call we decide to separate plugins to keep it simple and clear

2024-05-10 10:10 UTC, donhardman approved these changes
Looks good for me

2024-05-10 11:20 UTC, merged